### ISSUE TITLE
KeyError: 'code' - not working anymore

### ISSUE THREAD

**Issue by TimoD87** [CJNE/pyporscheconnectapi#37] opened 2023-11-04 11:47 UTC
Getting Error:

`Traceback (most recent call last):
  File "/home/pi/pypo-main/cli.py", line 4, in <module>
    cli()
  File "/home/pi/pypo-main/pyporscheconnectapi/cli.py", line 270, in cli
    loop.run_until_complete(main(args))
  File "/usr/local/lib/python3.11/asyncio/base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/home/pi/pypo-main/pyporscheconnectapi/cli.py", line 67, in main
    data = await client.getCurrentOverview(vin)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/pi/pypo-main/pyporscheconnectapi/client.py", line 460, in getCurrentOverview
    progressResult = await self._connection.post(
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/pi/pypo-main/pyporscheconnectapi/connection.py", line 246, in post
    headers = await self._createhead(application)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/pi/pypo-main/pyporscheconnectapi/connection.py", line 291, in _createhead
    token = await self._requestToken(
            ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/pi/pypo-main/pyporscheconnectapi/connection.py", line 206, in _requestToken
    await self._login()
  File "/home/pi/pypo-main/pyporscheconnectapi/connection.py", line 183, in _login
    self.auth_state["code"] = params["code"][0]
                              ~~~~~~^^^^^^^^
KeyError: 'code'`

Anyone a fix for this or a workaround? Maybe Polling Time Settings?

**Comment by Jmi91** [comment] 2023-11-04 12:57
Same problem for me...

**Comment by MarkusGH** [comment] 2023-11-04 17:57
Same here:

porschecli overview -v "WP1ZZZ..."

gives me

Traceback (most recent call last):
  File "/usr/local/bin/porschecli", line 8, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.8/dist-packages/pyporscheconnectapi/cli.py", line 270, in cli
    loop.run_until_complete(main(args))
  File "/usr/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/usr/local/lib/python3.8/dist-packages/pyporscheconnectapi/cli.py", line 67, in main
    data = await client.getCurrentOverview(vin)
  File "/usr/local/lib/python3.8/dist-packages/pyporscheconnectapi/client.py", line 464, in getCurrentOverview
    f"https://api.porsche.com/service-vehicle/{self.locale_str}/vehicle-data/{vin}/current/request/{progressResult['requestId']}/status"
KeyError: 'requestId'
ERROR:asyncio:Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x7fcbcc275520>
ERROR:asyncio:Unclosed connector
connections: ['[(<aiohttp.client_proto.ResponseHandler object at 0x7fcbcc2918e0>, 5172133.566873318)]', '[(<aiohttp.client_proto.ResponseHandler object at 0x7fcbcc2554c0>, 5172133.873355753)]']
connector: <aiohttp.connector.TCPConnector object at 0x7fcbcc2756a0>

Yesterday and the day before already errors, but manual login and solving the captcha helped.
Today it dies not helt anymore.

Looks like they are either fiddling around or voluntarily blocking access.

**Comment by MarkusGH** [comment] 2023-11-04 18:06
Try to login via web browser and solve the captcha.
Also car going to privacy mode gives problems (check in porsche app).

**Comment by TimoD87** [comment] 2023-11-04 19:53
> Try to login via web browser and solve the captcha. Also car going to privacy mode gives problems (check in porsche app).

Login via Web Login with Capatcha from same IP is working, error is still there - car has no privacy on

**Comment by MarkusGH** [comment] 2023-11-04 19:54
Log out/in again until no captcha is shown.

**Comment by fastlorenzo** [comment] 2023-11-04 23:18
Same here, if I switch IP (using VPN), no captcha is shown and this is working. We should identify what's the threshold in term of polling (which I believe is what is in place to force a captcha).

**Comment by MarkusGH** [comment] 2023-11-05 09:37
> Same here, if I switch IP (using VPN), no captcha is shown and this is working. We should identify what's the threshold in term of polling (which I believe is what is in place to force a captcha).

IMHO there is such an easy thing like a threshold. [evcc ](https://github.com/evcc-io/evcc) uses also uses the Porsche API (with refresh tokens), and when my car is not polled for like 12 hours the captcha still shows the next morning.

**Comment by Dual01** [comment] 2023-11-10 12:15
Since a few days, it does not work for me either. Here is the error message:
Traceback (most recent call last):
  File "/home/pi/.local/bin/porschecli", line 10, in <module>
    sys.exit(cli())
  File "/home/pi/.local/lib/python3.7/site-packages/pyporscheconnectapi/cli.py", line 270, in cli
    loop.run_until_complete(main(args))
  File "/usr/lib/python3.7/asyncio/base_events.py", line 584, in run_until_complete
    return future.result()
  File "/home/pi/.local/lib/python3.7/site-packages/pyporscheconnectapi/cli.py", line 81, in main
    data = await client.getEmobility(vin, model=args.model)
  File "/home/pi/.local/lib/python3.7/site-packages/pyporscheconnectapi/client.py", line 534, in getEmobility
    data = await self.getCapabilities(vin)
  File "/home/pi/.local/lib/python3.7/site-packages/pyporscheconnectapi/client.py", line 494, in getCapabilities
    f"https://api.porsche.com/service-vehicle/vcs/capabilities/{vin}"
  File "/home/pi/.local/lib/python3.7/site-packages/pyporscheconnectapi/connection.py", line 237, in get
    headers = await self._createhead(application)
  File "/home/pi/.local/lib/python3.7/site-packages/pyporscheconnectapi/connection.py", line 292, in _createhead
    application, wasExpired=(token is not None)
  File "/home/pi/.local/lib/python3.7/site-packages/pyporscheconnectapi/connection.py", line 206, in _requestToken
    await self._login()
  File "/home/pi/.local/lib/python3.7/site-packages/pyporscheconnectapi/connection.py", line 183, in _login
    self.auth_state["code"] = params["code"][0]
KeyError: 'code'
ERROR:asyncio:Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x734c76b0>
ERROR:asyncio:Unclosed connector
connections: ['[(<aiohttp.client_proto.ResponseHandler object at 0x734ce068>, 5497252.017260205)]']
connector: <aiohttp.connector.TCPConnector object at 0x734c75f0>

What could be the problem? Logging in via the website works

**Comment by MarkusGH** [comment] 2023-11-10 12:18
As written above a captcha is a common problem.
Sometimes you have to log on/off multiple times from the same IP until no captcha is shown.

**Comment by Dual01** [comment] 2023-11-10 12:43
ah ok, got it. Thanks

**Comment by Dual01** [comment] 2023-11-19 10:05
The problem is that even after several log on/offs, it works for several hours and then I am asked again for a captcha and I get the message: keyerror: code.

**Comment by fredriklj** [comment] 2023-11-22 15:05
Duplicate of #37

**Closed by fredriklj** 2023-11-22 15:05 UTC
